<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Update  PendingDelete</name>
   <tag></tag>
   <elementGuidId>1c6b525b-8d4a-43f6-94d2-92bf5cafa352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div/table/tbody/tr[10]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;27 1 1 Update Pending Delete&quot;i] >> internal:role=cell >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>94d6d214-1946-471f-9c44-dbd9c28a8516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex flex-column align-items-center justify-content-center button-group</value>
      <webElementGuid>9f15c06b-9905-42af-a808-fda1cdbebdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update  PendingDelete</value>
      <webElementGuid>6004a067-ce06-4808-bafb-4836cb1a6fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-container collapsed&quot;]/div[@class=&quot;content-area&quot;]/div[@class=&quot;manage-jobs container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;job-table table table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;table-row&quot;]/td[@class=&quot;d-flex flex-column align-items-center justify-content-center button-group&quot;]</value>
      <webElementGuid>b88f0f18-9848-43a6-b551-301a688d0f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/table/tbody/tr[10]/td[4]</value>
      <webElementGuid>2a2f4321-b323-4752-8177-2786d2057f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[9]/following::td[4]</value>
      <webElementGuid>6685adc6-d435-4a68-89cc-cbe77865a5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[4]</value>
      <webElementGuid>098838ba-63b2-4420-9296-a1602e8e14cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Update  PendingDelete' or . = 'Update  PendingDelete')]</value>
      <webElementGuid>6c93f5a2-9ad5-443a-9ae5-61393ee16488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
