<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pending</name>
   <tag></tag>
   <elementGuidId>3d7ac390-6791-41a1-a542-82c025413899</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.m-2.btn.btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;4 Software Developer Pendidikan Min S1 Teknik Informatika / Sistem informatika / Teknik Elektro Memiliki kemampuan untuk bahasa pemprograman Phyton / C# Memahami struktur dan konsep dasar dalam Odoo framework Mengerti cara modul-modul bekerja dalam system ERP dan berinteraksi satu sama lain Update Pending Delete&quot;i] >> internal:role=button >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51193e89-ff60-48db-bccb-bbdc7ac13885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bb816e62-9263-4b4f-9ac4-bae9587f2955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-2 btn btn-secondary</value>
      <webElementGuid>340defb5-acb4-49a3-b381-b7e82ada529d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Pending</value>
      <webElementGuid>02824bc7-73f2-49eb-8db7-dbcd002cfdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content-area&quot;]/div[@class=&quot;manage-jobs container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;job-table table table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;table-row&quot;]/td[@class=&quot;d-flex flex-column align-items-center justify-content-center button-group&quot;]/button[@class=&quot;m-2 btn btn-secondary&quot;]</value>
      <webElementGuid>93d2a8f3-b303-4e24-87ef-6851c8b9f370</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>d05e0d09-49c0-443c-b894-e07123bc1ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/table/tbody/tr/td[4]/button[2]</value>
      <webElementGuid>90da1b9b-28a7-4fdc-9c89-652e2781bcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[1]/following::button[1]</value>
      <webElementGuid>eba6610f-8296-4617-bc70-6fe438cbddab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software Developer'])[1]/following::button[2]</value>
      <webElementGuid>1465b0f6-a037-46f4-8980-b805b95c98cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::button[1]</value>
      <webElementGuid>9b5694c3-52e0-4121-800c-d0b8055b11ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT Business Analyst'])[1]/preceding::button[2]</value>
      <webElementGuid>ac6174be-6d4f-459b-b386-addbdb43c5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pending']/parent::*</value>
      <webElementGuid>2bbebc53-b8b1-4fa2-b4f8-1e34fc9505e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button[2]</value>
      <webElementGuid>1adb7526-dd28-469c-b72a-31c1da7cd63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '  Pending' or . = '  Pending')]</value>
      <webElementGuid>f4dbf7d1-6a26-438b-824b-40261ba0a858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
