<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reset</name>
   <tag></tag>
   <elementGuidId>d9d5d82c-c63b-4740-ba27-c2fa1364babd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.filter-button.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Reset&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e4240ca6-1ec8-4e7f-b164-ab70fe104711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2d2b3e4-4296-4d81-a86b-7ba17657d810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-button btn btn-primary</value>
      <webElementGuid>8df0dde6-4b09-4402-9363-adaf9f50b46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>bfea5e7e-3e6b-4711-aa6f-ed3c2f377853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content-area&quot;]/div[@class=&quot;dashboard-container container-fluid animated&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7&quot;]/form[@class=&quot;filter-form mb-4&quot;]/div[@class=&quot;align-items-center row&quot;]/div[@class=&quot;d-flex align-items-end col-md-2&quot;]/button[@class=&quot;filter-button btn btn-primary&quot;]</value>
      <webElementGuid>ba0bcc98-565c-4fe9-a3ca-466e348a37e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>6552cb0c-1b8b-4e73-8399-27b1e191f94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/form/div/div[4]/button</value>
      <webElementGuid>e106c4ec-75dc-4add-af3e-78675aafdfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position'])[1]/following::button[1]</value>
      <webElementGuid>931e27b9-4360-4cdc-b55a-c98824d71fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/following::button[2]</value>
      <webElementGuid>c72801ab-5fe6-41dc-a350-291fd95bea10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Info'])[1]/preceding::button[1]</value>
      <webElementGuid>08d2720e-4089-447b-9b3b-10b7f6c0ce24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/preceding::button[1]</value>
      <webElementGuid>ec99ee7d-46e3-456c-8d54-7e140a50ec83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reset']/parent::*</value>
      <webElementGuid>3163f237-1d63-4298-85c2-91dec4f7379e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>3c89d995-8ed6-42ca-b8af-528c9a340d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Reset' or . = 'Reset')]</value>
      <webElementGuid>a7887331-114d-4033-ac13-6fb4eedd15bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
