<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date_filter-input form-control _e5df8f</name>
   <tag></tag>
   <elementGuidId>985d0213-f16b-48b5-ae13-ac03e3b1292f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.filter-input.form-control.react-datepicker-ignore-onclickoutside</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcaf79e0-72ec-4e29-83ca-b352fe77d90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5ebddea-f387-472f-9e0e-ccfde895b23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input form-control react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>8c9ba7b3-5783-45fb-a576-a43ab3d4d44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content-area&quot;]/div[@class=&quot;dashboard-container container-fluid animated&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7&quot;]/form[@class=&quot;filter-form mb-4&quot;]/div[@class=&quot;align-items-center row&quot;]/div[@class=&quot;filter-item col-md-3&quot;]/div[1]/div[@class=&quot;react-datepicker-wrapper&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/input[@class=&quot;filter-input form-control react-datepicker-ignore-onclickoutside&quot;]</value>
      <webElementGuid>22d884b7-d539-4ee2-a3cf-54fcac327f74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>b9a94492-f25a-4ece-a8bd-b65218b5b837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/form/div/div/div/div/div/input</value>
      <webElementGuid>fa4e5667-99dd-40e9-95c6-97bacd87f601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>824ed08c-4233-443f-a357-55f6e26e8b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>278bd43a-7953-43e8-950b-d42efbed245d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
