<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Third Skill Needed_thirdHardSkill</name>
   <tag></tag>
   <elementGuidId>67ce35d1-78f0-4c70-ad05-cc28346290b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thirdHardSkill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='thirdHardSkill']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Third Skill Needed?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7106a102-2642-4b80-b1ff-d348a5be3594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thirdHardSkill</value>
      <webElementGuid>5294e5ff-45b0-45e3-965e-06d1e586ef90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bde44f17-7892-4005-ad36-8939956bcaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thirdHardSkill</value>
      <webElementGuid>bed3bab8-1ea4-421c-9339-bf0ae8a02894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-modern form-control</value>
      <webElementGuid>95e4312e-b7b0-4b4b-887b-037ec614b573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thirdHardSkill&quot;)</value>
      <webElementGuid>e20fc32b-cd89-4ba2-a21b-75b83949e215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='thirdHardSkill']</value>
      <webElementGuid>2bcf3fcf-e00c-4123-aaa7-ab612f77f2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div[2]/div[3]/div/input</value>
      <webElementGuid>bdc883ec-b284-4ea7-979a-86427abd3f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a1c265f4-d817-4169-832f-702dff3d9bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'thirdHardSkill' and @type = 'text' and @id = 'thirdHardSkill']</value>
      <webElementGuid>1b6bcf17-53a2-4b4c-9652-c4b17b39f585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
