<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maximum Industry Experience Needed_ma_d5a60e</name>
   <tag></tag>
   <elementGuidId>79a72a0e-6107-4744-a754-eea262d214f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxIndustryExperience</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxIndustryExperience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Maximum Industry Experience Needed?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65c38204-1f91-4cdd-9ff6-9999849e08a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>27ec16b0-06f7-4f0f-8709-84aca4ffd3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8bf87b9f-a691-4bb1-8e2d-b5f90266dcb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxIndustryExperience</value>
      <webElementGuid>c22ac32c-c4bb-484f-bcfc-3f8149c00bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>450ae20c-6bc6-4b89-9791-eb123754d48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxIndustryExperience</value>
      <webElementGuid>72f72b93-6a93-47a9-bdac-7d927c49e615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-modern form-control</value>
      <webElementGuid>59c019a3-f291-463d-adfa-85a4444c32e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxIndustryExperience&quot;)</value>
      <webElementGuid>955b53ec-3fe5-4492-87cc-e7833ada59be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxIndustryExperience']</value>
      <webElementGuid>1f54195b-c97d-407b-a97a-9a07f80392dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div[2]/div[2]/div/input</value>
      <webElementGuid>c0cd5ea2-9193-4a9f-995c-8a20ca1b9281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>6a2323ec-c37b-436c-ade5-8cd163287921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'maxIndustryExperience' and @type = 'number' and @id = 'maxIndustryExperience']</value>
      <webElementGuid>d821f5fb-c844-4146-af12-f1e73a69c9bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
