<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maximum Position Experience Needed_ma_1ac951</name>
   <tag></tag>
   <elementGuidId>6b22af94-9bf6-4425-974b-c4196388536a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxPositionExperience</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxPositionExperience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Maximum Position Experience Needed?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cb23cc0-c274-48cb-a4db-2d63d9c865bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>31632c3f-ce98-4d67-bdfe-9faf36dcddec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a06cbdc6-f5b5-49a4-a05d-7c3506a31a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxPositionExperience</value>
      <webElementGuid>32ad8adc-756b-4e33-a2b0-c4c68d139259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2d6919b2-f9b5-4193-8c11-1f2e5e8f3171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxPositionExperience</value>
      <webElementGuid>1597f35f-4a52-4324-b7b5-8b5afa39e396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-modern form-control</value>
      <webElementGuid>e807e4df-e120-46d2-a8d7-71694c6d1525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxPositionExperience&quot;)</value>
      <webElementGuid>5f0f5ce3-1ea9-4e66-964a-93ce026bd19f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxPositionExperience']</value>
      <webElementGuid>17e86810-7f18-478e-8116-95d3ec616bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div/div[2]/div/input</value>
      <webElementGuid>7d8f5e65-cae8-40c4-9a10-90676e0f05da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>363ac842-1797-43f2-9a96-64840d4104fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'maxPositionExperience' and @type = 'number' and @id = 'maxPositionExperience']</value>
      <webElementGuid>b5d070c1-fe87-42aa-9dfe-2c585f79553b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
