<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maximum Salary Needed_maxSalary</name>
   <tag></tag>
   <elementGuidId>6382bcbd-860c-4aef-b370-3747b85ce9d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxSalary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxSalary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Maximum Salary Needed?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07b9732e-cbae-4b27-a68e-c339833917a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f4230cba-485f-40e6-a2b4-71fb6ce4fd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>50000</value>
      <webElementGuid>97608b63-c1e6-4de8-a953-e9d42da454cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxSalary</value>
      <webElementGuid>b806ad2c-bb0a-4843-a78a-5a9fc7422029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ade01601-0930-4420-bdb7-f3af15d77f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxSalary</value>
      <webElementGuid>28141484-7fe5-4a16-8cb5-cc02b3ad3394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-modern form-control</value>
      <webElementGuid>89005804-c847-47b3-b361-faa4ea93f50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxSalary&quot;)</value>
      <webElementGuid>9d0f3cdf-96ef-4ee4-93cc-9bcf292cffab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxSalary']</value>
      <webElementGuid>eedefa55-1174-47ca-93b5-7d1a466eaae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div[3]/div[2]/div/input</value>
      <webElementGuid>fed1ee59-9ccf-49f2-beeb-dae500ce174f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>1e4cff62-b4e0-4820-9b6e-9db525088923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'maxSalary' and @type = 'number' and @id = 'maxSalary']</value>
      <webElementGuid>f25669d2-96f3-49c0-b0a7-819059fccd6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
