<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Second Skill Needed_secondHardSkill</name>
   <tag></tag>
   <elementGuidId>2f941317-611f-42f0-a4c2-12e2608572a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondHardSkill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Second Skill Needed?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8050306c-b7ed-405b-8923-cb789e02f796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondHardSkill</value>
      <webElementGuid>1be290a9-afd7-435d-b488-442a87d965bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7eca2b31-2e1d-406e-b91c-db9c521bb6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondHardSkill</value>
      <webElementGuid>b7b7d591-df30-4f51-a5e0-876449136b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-modern form-control</value>
      <webElementGuid>ec3c930a-2a98-4623-a19f-581b809f8d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondHardSkill&quot;)</value>
      <webElementGuid>dbbd1095-f0a3-406e-8f84-cc26d06e6dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondHardSkill']</value>
      <webElementGuid>2bf0c68a-8641-4881-b555-d1126b09317c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div[2]/div[2]/div/input</value>
      <webElementGuid>68313857-dd7f-45a9-885b-543a33ceafca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a3cfe34b-58af-4149-99d2-a38ae1330a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'secondHardSkill' and @type = 'text' and @id = 'secondHardSkill']</value>
      <webElementGuid>fd03ec0f-bca8-49f2-8551-092a0b250d41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
