<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Skill Needed_firstHardSkill</name>
   <tag></tag>
   <elementGuidId>584cc38d-fc1f-4eb4-96d3-2a59d0821760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstHardSkill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstHardSkill']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First Skill Needed?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>125e9715-8eb2-4360-877f-5007d236d79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstHardSkill</value>
      <webElementGuid>560ac604-063e-4ec4-b6b8-72874dc56ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70096362-bd22-41df-aa62-c91aac679bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstHardSkill</value>
      <webElementGuid>e1936745-c183-4fc3-87f6-26df968c1fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-modern form-control</value>
      <webElementGuid>353806eb-3acc-4555-b29f-2b67e92447e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstHardSkill&quot;)</value>
      <webElementGuid>d1e56bb3-c2ed-4f89-b211-e0166edfe20e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstHardSkill']</value>
      <webElementGuid>0045deef-3cf9-4430-a8d3-93ce465dc936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div[2]/div/div/input</value>
      <webElementGuid>5ddd8ec4-4989-4ff2-acfd-3c7c6c40dd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>a77d057c-85d1-4923-b663-ef4bdb0eb906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'firstHardSkill' and @type = 'text' and @id = 'firstHardSkill']</value>
      <webElementGuid>2f67aec9-19b7-41d4-8022-81eaa7698d12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
