<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Languages Needed_english</name>
   <tag></tag>
   <elementGuidId>11e04f25-38b5-4dc7-917e-0c361de83f2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#english-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='english-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;English&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b652e0d-65b3-40c1-a3b2-fac938a7a351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>english</value>
      <webElementGuid>d3274a30-2e5a-4fff-ada9-085fd7776224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>afc9b726-0ad5-4ab5-a740-a4b8f2aec2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>english-checkbox</value>
      <webElementGuid>6011fba3-18e9-4f9c-a440-b2197592f3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>51f50d6a-e425-4726-8ca0-aa038ac19a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;english-checkbox&quot;)</value>
      <webElementGuid>a1db815a-0a0c-46a4-915c-b8834fc41d36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='english-checkbox']</value>
      <webElementGuid>f50228f9-97b3-43a6-95ef-eca558b22a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div/div/div/input</value>
      <webElementGuid>dcebe939-2c0a-4eaf-8823-71556ecc98f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e4167718-6817-4210-8c2c-84f28c57a320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'english' and @type = 'checkbox' and @id = 'english-checkbox']</value>
      <webElementGuid>96dbad0a-3c54-4c52-986c-0d40ea34e8ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
