<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Professional Hire_jobAimed</name>
   <tag></tag>
   <elementGuidId>c10637d0-64e0-4e96-af17-b3832db40ddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobAimedFreshGraduate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobAimedFreshGraduate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Fresh Graduate Hire&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea4c6156-9990-48fb-bb50-fbe683379730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobAimed</value>
      <webElementGuid>6787c042-d78d-4b8f-973b-eef1bb3bb9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>37328e47-8160-44cf-b393-81ad4a4bfa15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobAimedFreshGraduate</value>
      <webElementGuid>64d36066-5765-4d0a-ab24-9528f867a4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>ef597f12-d556-47cc-9fdc-aeccfae4c9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Fresh Graduate</value>
      <webElementGuid>32d64f48-a303-4f20-956a-72097eef0390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobAimedFreshGraduate&quot;)</value>
      <webElementGuid>40d0637b-a5aa-4fc2-87c0-c2179d1f1e48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobAimedFreshGraduate']</value>
      <webElementGuid>cb96ee9a-9665-44ff-a8e7-e71666d7e22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>91aa6f44-2739-4aa0-828b-0d4d2a490a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1353eb64-133a-485d-9dc3-9a17e80f5972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'jobAimed' and @type = 'radio' and @id = 'jobAimedFreshGraduate']</value>
      <webElementGuid>645c6001-b7b0-4a69-a8cd-fa6f194281a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
