<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Division_jobType</name>
   <tag></tag>
   <elementGuidId>0c8463e0-3948-4a0f-98d2-dac842ebb0b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Job Division?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a92a49d5-369c-4e04-b86d-6fc7b4d49ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobType</value>
      <webElementGuid>3b121df9-3bca-4978-8f45-e21d5a29274c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94b52dcd-7bd5-443f-8224-544d2d2911e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobType</value>
      <webElementGuid>2806295d-b937-490d-aef2-1191224639ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-modern form-control</value>
      <webElementGuid>4b8d7ad0-7f8f-4f4b-938b-26630ce051b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobType&quot;)</value>
      <webElementGuid>b875d02e-6157-4acf-aeda-607a8652b0ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobType']</value>
      <webElementGuid>44c413d2-91d0-4c44-adc7-d3bb1bd49c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div[2]/div[2]/div/input</value>
      <webElementGuid>bef68a88-2ee8-4e35-97ad-4d158adf13ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>6171213c-a1bc-449d-94d4-932938e47e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'jobType' and @type = 'text' and @id = 'jobType']</value>
      <webElementGuid>cd66da69-6ab0-48bf-a21f-4edc38a9105d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
