<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Languages Needed__mandarin</name>
   <tag></tag>
   <elementGuidId>e4255e6f-ea8d-480f-8565-0547c0c0ddb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mandarin-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mandarin-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Mandarin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df36d674-69af-46cb-af9a-c4e241bb4e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mandarin</value>
      <webElementGuid>70d6549c-0401-404d-ab73-b56457fcdfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ef3ee5b7-fc89-40fc-b057-172b007a8271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mandarin-checkbox</value>
      <webElementGuid>373978f3-a29c-4f43-9577-7a864242a0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>cd9201cc-d945-4d49-b7b0-1d9848e6abbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandarin-checkbox&quot;)</value>
      <webElementGuid>58dbfe41-18b6-4498-bfed-109b552f2af5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mandarin-checkbox']</value>
      <webElementGuid>d53949a2-2b99-4b91-8a25-c051b49fa706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>21375cb3-b7e5-4cba-a36a-5188027ac4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>81218bbc-d65c-411b-9fa7-f682cac4b854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'mandarin' and @type = 'checkbox' and @id = 'mandarin-checkbox']</value>
      <webElementGuid>7f8fa9b8-5660-4005-ba0a-5c71e5319598</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
