<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Name_jobName</name>
   <tag></tag>
   <elementGuidId>83e6d4c1-e6f5-48f9-aede-ba9720ac0eca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Job Name?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe256838-4a30-4214-8142-a68636c8905c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobName</value>
      <webElementGuid>8ce2138a-e067-41c5-a217-e707e6739022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dccb3458-17e3-444f-8359-a0747bf50ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobName</value>
      <webElementGuid>2b0a807c-098d-4919-a14b-1db0a824924c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-modern form-control</value>
      <webElementGuid>15aa70f7-9a8f-4b7a-b0ba-93287a5c8b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobName&quot;)</value>
      <webElementGuid>59c696b8-5c49-4d39-af71-b6e0dbef7b3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobName']</value>
      <webElementGuid>a830db9e-f488-4dc6-8ce1-3e392700c0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>4388374b-5ba6-4be8-8777-309390d9a8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>db9c4a3b-bae9-40d7-9f52-4f566fe1796e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'jobName' and @type = 'text' and @id = 'jobName']</value>
      <webElementGuid>5a1b0a0d-f256-40fa-886d-f906b8df9fe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
