<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimum Position Experience Needed_mi_0426d8</name>
   <tag></tag>
   <elementGuidId>90d9f506-0357-46aa-89c3-165e00b23e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#minPositionExperience</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='minPositionExperience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Minimum Position Experience Needed?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89d1a35d-ba42-4920-bc67-556587e30065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3f5cf339-d5b2-479b-8c6b-77e38199f639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f58f9742-1884-43d4-8d6e-04e5ebdda7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>minPositionExperience</value>
      <webElementGuid>deef5ccb-ef09-48b4-bed7-2b9efe267521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c52ab636-942d-47d6-8003-dff6b678315a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>minPositionExperience</value>
      <webElementGuid>33e74894-a44a-4502-ab91-bd92fe438151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-modern form-control</value>
      <webElementGuid>68080970-e433-4c11-bf24-499ac8fd84b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minPositionExperience&quot;)</value>
      <webElementGuid>53038fab-cce5-4fc8-b6e3-7641f2151c88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='minPositionExperience']</value>
      <webElementGuid>cdb8db70-5230-4f4c-bfe1-2ba334ff3298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div/div/div/input</value>
      <webElementGuid>cca35680-051c-4946-8acb-4ea0192aee28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d1f36bc8-22e1-4253-8bac-dcf22c876f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'minPositionExperience' and @type = 'number' and @id = 'minPositionExperience']</value>
      <webElementGuid>a2280c8f-20f7-4ef0-b28b-74b0f2a3ed72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
