<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All GradeFresh GraduateProfessional</name>
   <tag></tag>
   <elementGuidId>a8a0b481-db9a-4564-b741-c7f4deb826c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='searchJobByGrade']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchJobByGrade</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#searchJobByGrade</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a367119f-52f5-4e1f-aa1d-69856ae625ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchJobStatus</value>
      <webElementGuid>a97444e9-1f15-4bae-a264-59a5ff5756f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>7551e87f-65fc-4f6b-8402-83b276de2ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchJobByGrade</value>
      <webElementGuid>c3c3b426-0a63-464a-9b06-c11360695f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All GradeFresh GraduateProfessional</value>
      <webElementGuid>271f956e-7dd7-45aa-87b1-9663131f0509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchJobByGrade&quot;)</value>
      <webElementGuid>f0f78a5d-fff4-4b7c-ac4c-c3ca84f5aa62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='searchJobByGrade']</value>
      <webElementGuid>8f73fea1-f5f2-4351-a5b1-b3643529490c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/select</value>
      <webElementGuid>76bb47e7-76be-40cb-9616-8649a1905947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORKING AT R17'])[1]/following::select[1]</value>
      <webElementGuid>7ff701dd-4f39-42cf-b104-e8c1e598d703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R17 Group Career'])[1]/following::select[1]</value>
      <webElementGuid>6c764673-dd6f-419c-9fbe-3355a0e308d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Professional Hire'])[1]/preceding::select[1]</value>
      <webElementGuid>39894cdc-5a7d-445c-875e-23aaef671aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d4079738-8b14-4421-9b19-8c2a64f40674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'searchJobStatus' and @id = 'searchJobByGrade' and (text() = 'All GradeFresh GraduateProfessional' or . = 'All GradeFresh GraduateProfessional')]</value>
      <webElementGuid>f3416106-41a5-4536-9319-05b49f94d6e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
