<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back to Career</name>
   <tag></tag>
   <elementGuidId>eddd9efe-f561-4cb3-9fb5-11dfefea97a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.back-btn.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Back to Career&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>498632af-c4eb-4ae8-87d0-a3f45eed191c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>423441ca-37c0-4d86-9b5b-cc7588fd5cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>back-btn btn btn-primary</value>
      <webElementGuid>1e59c8c2-15b8-43e8-baab-34898a303ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to Career</value>
      <webElementGuid>fb8f42d4-11c6-46de-92ca-0930ccb93ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;d-flex flex-column justify-content-center mt-1 p-3 container-fluid&quot;]/div[@class=&quot;position-relative w-100 d-flex justify-content-between align-items-center my-2  row&quot;]/div[@class=&quot;d-flex justify-content-center align-items-center col&quot;]/button[@class=&quot;back-btn btn btn-primary&quot;]</value>
      <webElementGuid>91c166dd-7684-4107-b74b-5855a4a0639b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>87f338aa-8926-4469-8349-bbc3b6253f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/button</value>
      <webElementGuid>1c4c039b-bc84-4e6b-8047-c6a83285cbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Details'])[1]/preceding::button[1]</value>
      <webElementGuid>b502c61c-c845-400d-b2f2-c9a48b911c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Position'])[1]/preceding::button[1]</value>
      <webElementGuid>d747f4e1-bcd4-4a9e-a862-43e74545ba10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back to Career']/parent::*</value>
      <webElementGuid>83536aeb-86fe-4653-a772-4e96927e6544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>99a95ac6-a422-4c6d-bf1f-2fc18ab20c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Back to Career' or . = 'Back to Career')]</value>
      <webElementGuid>978aa30b-02ce-4877-b96a-75425b8d0931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
