<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_applicantEmail</name>
   <tag></tag>
   <elementGuidId>dbd2f451-8770-4c79-8a45-0c8ecff446bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formApplicantEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formApplicantEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>535f4503-8b88-48af-ab54-c6f8c52b5e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>a687c797-e064-423f-89c8-714307f9e60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applicantEmail</value>
      <webElementGuid>593c2a1c-8a76-4189-8526-af59e7caf349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>24f571dd-59fd-47ad-af99-7ee856a50dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formApplicantEmail</value>
      <webElementGuid>030696e7-7a13-4de1-9a9f-2991f27a161a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b696e2ea-2e9b-48e8-8d62-99237582c670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fc5d96fe-77ec-4e1d-9f95-863f214ab2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formApplicantEmail&quot;)</value>
      <webElementGuid>60d34d8d-b09f-44e1-8eda-a6f368025b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formApplicantEmail']</value>
      <webElementGuid>ab9e5728-c151-4877-b9b7-c31856957db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/form/div[2]/div/div/input</value>
      <webElementGuid>cd4f9c69-3f3e-49b0-82ad-0d102832529d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>99532503-a9bf-4037-95f1-8c7ba9a1a938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your email' and @name = 'applicantEmail' and @type = 'email' and @id = 'formApplicantEmail']</value>
      <webElementGuid>2c82f628-3d3e-4568-b155-8e7fff0e8f38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
