<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_applicantName</name>
   <tag></tag>
   <elementGuidId>c539c120-0b77-4555-8f9d-6e0e25eabb15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formApplicantName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formApplicantName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce670dbc-5b97-486e-a3fb-cfa21a17e176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your name</value>
      <webElementGuid>36d663c1-0bdf-4a57-a30a-d08c4a792869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applicantName</value>
      <webElementGuid>e69cb317-9cbf-4da5-a547-7e89315ca3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf2e1c36-aa80-4d0f-8c2d-bf190df437a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formApplicantName</value>
      <webElementGuid>e404646b-e901-40b2-bb19-9660c7ee7afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6eae04ad-8a22-4a66-894b-3d66bc358d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formApplicantName&quot;)</value>
      <webElementGuid>170bece6-3ffe-436c-80ef-04b1da603265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formApplicantName']</value>
      <webElementGuid>1b779a89-bbc2-4ecc-8a74-73405861c8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/form/div/div/input</value>
      <webElementGuid>c58fb885-67c6-4496-8b3e-04fb05060cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>32561ec7-8af0-45d1-844f-47a698225072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your name' and @name = 'applicantName' and @type = 'text' and @id = 'formApplicantName']</value>
      <webElementGuid>d87c9323-9123-414c-a450-169c373e6fbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
