<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unggah CV anda_resume</name>
   <tag></tag>
   <elementGuidId>6e072271-cc52-4b9e-807c-32975362efe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formResume</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formResume']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Unggah CV anda&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a091e63-6553-4f4f-abbf-90f04740fa21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf</value>
      <webElementGuid>c5242c01-239a-40f9-98fe-23e714671dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>resume</value>
      <webElementGuid>92a088fe-194b-48a4-a38e-13bef1aa5ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>8cdeb030-04a4-4493-a806-7536a0f4a098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formResume</value>
      <webElementGuid>0f6e0e19-d92e-4140-b94c-b4f9d46b4a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-input form-control</value>
      <webElementGuid>4eae12e6-4504-4fc4-a748-302f70d60ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formResume&quot;)</value>
      <webElementGuid>a5bfdf5b-9be5-4f64-a53f-da429485e6a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formResume']</value>
      <webElementGuid>09a7e6c8-501f-4ac6-9fc8-beecbdb4685d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/form/div[5]/div/div/div/input</value>
      <webElementGuid>dab501f4-0e32-48d6-8e22-be6198e38e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>b2ef7e18-05ee-4aca-8572-388fe6694017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'resume' and @type = 'file' and @id = 'formResume']</value>
      <webElementGuid>ffebe293-07f8-4354-925f-e7bc2b08f3f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
