<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How Long Have You Been Involved in Th_a6d4d9</name>
   <tag></tag>
   <elementGuidId>463d7cf2-2a2b-4212-a8f0-fd80ca1cf0c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formJobExperience</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formJobExperience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Answer your work experience here...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39ee6fd5-6e65-4e67-9401-c8f38fa7abe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>18527b67-ae81-4b8c-a287-df31fb858a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>866808c2-07b1-4df6-9d3b-12eaad6709a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Answer your work experience here...</value>
      <webElementGuid>2a1f80e3-6ff4-43d4-b33a-3058322ab6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobExperience</value>
      <webElementGuid>9153c652-cc08-4117-812f-42ca3e3428ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e00e93a4-2386-4210-a45d-4a7cb15e2fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formJobExperience</value>
      <webElementGuid>fee6b6e8-67bd-4766-b91e-79eeb24e2225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ae1bb012-cac2-44a8-86b5-b740574f39c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formJobExperience&quot;)</value>
      <webElementGuid>f0f09a03-f142-4469-b7ed-d996df6ef2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formJobExperience']</value>
      <webElementGuid>e8fb31ab-daa6-4cd9-9be2-83d336a39c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/form/div[2]/div/div/input</value>
      <webElementGuid>01bb4998-f0fb-4d44-9a6b-e37e937ea99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>89d6082c-d11f-4cf5-bb5a-13354fdee559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Answer your work experience here...' and @name = 'jobExperience' and @type = 'number' and @id = 'formJobExperience']</value>
      <webElementGuid>c2939e46-cffa-4b81-8b8a-cd3909de0e3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
