<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How many years of experience do you h_916e13</name>
   <tag></tag>
   <elementGuidId>41aea403-339b-41e0-8228-4cc1d6de29b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondHardSkillExperience</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondHardSkillExperience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;How many years of experience do you have with JavaScript?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdd659e3-ab43-46d2-8841-c7fdcccfd622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25fa58a8-26a3-4c08-bd16-97d3aa4b065e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>203e8342-aeb9-4d64-8073-0243b12b2346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Years of experience</value>
      <webElementGuid>d9e1e94c-0513-4097-bd0f-7894551fa9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondHardSkillExperience</value>
      <webElementGuid>19fd290d-2d1b-4c0b-9e85-0f75ca29acd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>dc032103-853b-471c-980a-3c862d0a8441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondHardSkillExperience</value>
      <webElementGuid>3abb3e42-8d5d-4ef8-a6f9-126c61cc5666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d57c987a-2909-48ba-8572-42c12f2d19d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondHardSkillExperience&quot;)</value>
      <webElementGuid>87a4678b-4fc9-4a75-98f4-3c11c3ecb028</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondHardSkillExperience']</value>
      <webElementGuid>3c27b11d-7657-4cd1-81be-4fc7e990c5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/form/div[2]/div/div/input</value>
      <webElementGuid>6eabe3a3-1f84-4715-8a2c-3aa8c1ffab25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>0afa81fd-6503-4951-97a4-1c3a32c33edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Years of experience' and @name = 'secondHardSkillExperience' and @type = 'number' and @id = 'secondHardSkillExperience']</value>
      <webElementGuid>9cbd9304-5732-4a36-ad6b-914b407c88d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
