<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How Much is Your Expected Salary_sala_954421</name>
   <tag></tag>
   <elementGuidId>906c0966-841f-453b-998c-d579326cedc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formSalaryExpectation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formSalaryExpectation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Answer your expected salary here...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2267e096-3dba-4c82-927c-b22ca3b32f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>639bd4fb-f09c-48bb-9292-efa81042fb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>50000</value>
      <webElementGuid>101b1bb7-ce67-4cb8-afe4-f2fb4f5c176b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Answer your expected salary here...</value>
      <webElementGuid>0da22d85-7602-44eb-a845-cbd32e2ddef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>salaryExpectation</value>
      <webElementGuid>d35a303b-4de4-417b-9df2-46587b87d3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>89b9c109-9822-450a-a6b3-fb3937c97898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formSalaryExpectation</value>
      <webElementGuid>b2046ed3-3de4-46df-8c74-e5c52b4a1288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b96c8181-7dda-48e1-9a77-324bd8c6223d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSalaryExpectation&quot;)</value>
      <webElementGuid>0c978160-2b18-48b6-8b7d-51c6d07ffe72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formSalaryExpectation']</value>
      <webElementGuid>172f0669-7707-4451-b3d8-63004c494f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/form/div[3]/div/input</value>
      <webElementGuid>ca9ee543-ea34-4d52-b85f-601649ee08c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>649ca3a4-bc90-42cd-bf57-d3f12f1b8832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Answer your expected salary here...' and @name = 'salaryExpectation' and @type = 'number' and @id = 'formSalaryExpectation']</value>
      <webElementGuid>7fc1d861-f8f7-4c33-a613-145fe6454c5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
