<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How many years of experience do you h_883aab</name>
   <tag></tag>
   <elementGuidId>0beeea60-47c3-4a9b-96d0-23beb8b06738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstHardSkillExperience</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstHardSkillExperience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;How many years of experience do you have with Python?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bf69c65-e07f-482b-a4db-ded3441c6a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4b8915e3-3e3b-42e9-9906-278b017f9b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>47b80a20-4d97-4df1-b486-ac65e559ec15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Years of experience</value>
      <webElementGuid>f5ebb527-2c50-43cf-bb6f-d771d69765f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstHardSkillExperience</value>
      <webElementGuid>864e9d1a-d64d-4987-8786-621ff1ff3a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c3216625-e12c-4751-a559-b94e147cb052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstHardSkillExperience</value>
      <webElementGuid>7d777633-d60b-452f-8cff-cc5d5f37fbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8992e27e-656f-4373-834b-44b4ec4bf24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstHardSkillExperience&quot;)</value>
      <webElementGuid>012a9625-48ad-4fd1-9e93-b0aa7f5e3aef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstHardSkillExperience']</value>
      <webElementGuid>3f14c5a4-c302-41a8-bf19-235859b3c226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/form/div/div/div/input</value>
      <webElementGuid>895a5796-fa98-4828-b892-c790de26aace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2a828be8-5f8b-49dc-85b8-cdc38c490bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Years of experience' and @name = 'firstHardSkillExperience' and @type = 'number' and @id = 'firstHardSkillExperience']</value>
      <webElementGuid>0b10fca0-408c-4bb3-9acc-e7d13b3df804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
