<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How Long Have You Been Involved in Th_795ed3</name>
   <tag></tag>
   <elementGuidId>22a77111-a70a-4a3f-9497-5e5663a70b32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formIndustryExperience</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formIndustryExperience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Answer your industry experience here...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aaa04bd7-12cf-4a04-993b-a017bca37c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aabcb330-a4c7-4e5d-a300-34558673912f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ce467cea-359a-4240-9cf3-bde3a02cea7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Answer your industry experience here...</value>
      <webElementGuid>a0ab6650-e9fb-4fe3-9d90-9a791a5e5eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>industryExperience</value>
      <webElementGuid>baeea871-bd1c-45fc-ad36-5c4d4c3b7c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>401e8ded-f2f3-48c0-bb05-3d0f2dc4a950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formIndustryExperience</value>
      <webElementGuid>2d333ef1-4627-421d-8d7e-dd02e40ce067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3420beae-6b9d-47b4-8e2e-18a0407aa681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formIndustryExperience&quot;)</value>
      <webElementGuid>e8dc69fc-86cc-44dd-932e-fbbad05ce010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formIndustryExperience']</value>
      <webElementGuid>42565244-4ee1-446f-99f4-0f4a5df440c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/form/div[2]/div[2]/div/input</value>
      <webElementGuid>cac6e7c8-dd6c-44e6-81f6-c54e0ea3dcaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>047da00c-16ff-4d63-a4f7-b5aa5132c50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Answer your industry experience here...' and @name = 'industryExperience' and @type = 'number' and @id = 'formIndustryExperience']</value>
      <webElementGuid>9b985be9-0a8e-4324-813d-8ed51098913f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
