<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How many years of experience do you h_c362bb</name>
   <tag></tag>
   <elementGuidId>48b6f62f-9864-440e-b8d9-724e798a95ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thirdHardSkillExperience</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='thirdHardSkillExperience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;How many years of experience do you have with PHP?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>470d502e-98a8-425f-b885-502ea749fa1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c87a823-7fab-4532-bbc1-07e25e121d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9e2e2952-2469-4bf7-bcac-4d133f9d9cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Years of experience</value>
      <webElementGuid>c2d2d786-c962-4ad6-859e-e6a40366a613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thirdHardSkillExperience</value>
      <webElementGuid>37eefd8c-9613-43ba-bb70-e4b3a72552f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3fedec00-9d2e-4892-a9f7-4e32b834e941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thirdHardSkillExperience</value>
      <webElementGuid>95cd5cd4-401e-46f1-8171-2f830a06c802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>43ade3d1-579a-4a3e-8428-ed3ad550bf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thirdHardSkillExperience&quot;)</value>
      <webElementGuid>3d3a92a7-c238-42d7-98ac-857325286a8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='thirdHardSkillExperience']</value>
      <webElementGuid>1d6104ee-e953-4c28-9a6a-46a89730df37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/form/div[3]/div/div/input</value>
      <webElementGuid>db6e64d8-11a4-44dd-80a5-02680c842355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>7e16a24d-4892-4f8b-81fb-350d220279b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Years of experience' and @name = 'thirdHardSkillExperience' and @type = 'number' and @id = 'thirdHardSkillExperience']</value>
      <webElementGuid>a53f3ffe-1b0c-4900-819e-0397ac59ca35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
