<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_English</name>
   <tag></tag>
   <elementGuidId>07261b05-1897-4772-bd47-0305cb8b4a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.form-check-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/form/div[4]/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;English&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>14c858df-2851-4af5-bb5c-45827cbe7d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>languages</value>
      <webElementGuid>5621fb43-bf4a-4a62-be25-5ca2d4bf5d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>0fd4aea4-a26c-41c1-bbe9-99a93ad80c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>fc8bc2a1-1dc0-4c44-bf96-207adee6da74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;d-flex flex-column justify-content-center mt-1 p-3 container-fluid&quot;]/div[@class=&quot;d-flex justify-content-center mx-auto row&quot;]/form[1]/div[@class=&quot;mb-2 row&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/div[@class=&quot;form-check&quot;]/label[@class=&quot;form-check-label&quot;]</value>
      <webElementGuid>ace78993-ffd4-423a-a905-3bc7e5ea886d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/form/div[4]/div/div/div/label</value>
      <webElementGuid>7f9fbba0-2764-49b7-9496-08ddb48560b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Which languages do you speak?'])[1]/following::label[1]</value>
      <webElementGuid>8af2fee6-cb3f-4427-a82c-be907ddc9eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandarin'])[1]/preceding::label[1]</value>
      <webElementGuid>4ae0d4b2-8e04-49cc-a8c7-50b4d640b913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah CV anda'])[1]/preceding::label[2]</value>
      <webElementGuid>57b8bdb8-1d06-4d23-8643-4add7768418a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>40ac08d0-02a3-479d-955f-c9f55251ff38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/label</value>
      <webElementGuid>18692a28-bb62-496e-8bf2-fdc21d434798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'English' or . = 'English')]</value>
      <webElementGuid>0a51819e-f239-42ec-a8da-c90299cf5ab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
